#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 23, 2018 10:07:27 AM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Accueil_support

import Produit,Client,Archive

ARCHIVE=0
CLIENT=0
PRODUIT=0

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Menu_Principal (root)
    Accueil_support.init(root, top)
    root.mainloop()

w = None
def create_Menu_Principal(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Menu_Principal (w)
    Accueil_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Menu_Principal():
    global w
    w.destroy()
    w = None


class Menu_Principal:
    def call_Archive(self,event):
        global ARCHIVE,PRODUIT,CLIENT
        if(ARCHIVE):
            Archive.destroy_Gerer_les_Archives()
            ARCHIVE=0
        if(PRODUIT):
            Produit.destroy_Gerer_les_Produits()
            PRODUIT=0 
        if(CLIENT):
            Client.destroy_Gerer_les_Clients()
            CLIENT=0       
        Archive.create_Gerer_les_Archives(root)
        ARCHIVE=1

    def call_Client(self,event):
        global ARCHIVE,PRODUIT,CLIENT
        if(ARCHIVE):
            Archive.destroy_Gerer_les_Archives()
            ARCHIVE=0
        if(PRODUIT):
            Produit.destroy_Gerer_les_Produits()
            PRODUIT=0 
        if(CLIENT):
            Client.destroy_Gerer_les_Clients()
            CLIENT=0       
        Client.create_Gerer_les_Clients(root)
        CLIENT=1

    def call_Produit(self,event):
        global ARCHIVE,PRODUIT,CLIENT
        if(ARCHIVE):
            Archive.destroy_Gerer_les_Archives()
            ARCHIVE=0
        if(PRODUIT):
            Produit.destroy_Gerer_les_Produits()
            PRODUIT=0 
        if(CLIENT):
            Client.destroy_Gerer_les_Clients()
            CLIENT=0       
        Produit.create_Gerer_les_Produits(root)
        PRODUIT=1 

    def call_Menu(self,event):
        global ARCHIVE,PRODUIT,CLIENT
        if(ARCHIVE):
            Archive.destroy_Gerer_les_Archives()
            ARCHIVE=0
        if(PRODUIT):
            Produit.destroy_Gerer_les_Produits()
            PRODUIT=0 
        if(CLIENT):
            Client.destroy_Gerer_les_Clients()
            CLIENT=0                  



    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Cambria Math} -size 14 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Showcard Gothic} -size 14 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"

        top.geometry("1129x668+81+11")
        top.title("Menu Principal")
        top.configure(background="#0b0b1c")
        top.resizable(0,0)



        self.labPara = Label(top)
        self.labPara.place(relx=0.0, rely=0.93, height=51, width=154)
        self.labPara.configure(activebackground="#f9f9f9")
        self.labPara.configure(activeforeground="black")
        self.labPara.configure(background="#0b0b1c")
        self.labPara.configure(cursor="hand2")
        self.labPara.configure(disabledforeground="#a3a3a3")
        self.labPara.configure(font=font9)
        self.labPara.configure(foreground="white")
        self.labPara.configure(highlightbackground="#d9d9d9")
        self.labPara.configure(highlightcolor="black")
        self.labPara.configure(relief=GROOVE)
        self.labPara.configure(text='''Parametres''')
        self.labPara.configure(width=154)

        self.labArch = Label(top)
        self.labArch.place(relx=0.0, rely=0.58, height=131, width=154)
        self.labArch.configure(activebackground="#f9f9f9")
        self.labArch.configure(activeforeground="black")
        self.labArch.configure(background="#0b0b1c")
        self.labArch.configure(borderwidth="1")
        self.labArch.configure(cursor="hand2")
        self.labArch.configure(disabledforeground="#a3a3a3")
        self.labArch.configure(font=font9)
        self.labArch.configure(foreground="white")
        self.labArch.configure(highlightbackground="#d9d9d9")
        self.labArch.configure(highlightcolor="black")
        self.labArch.configure(relief=RAISED)
        self.labArch.configure(text='''Archives''')
        self.labArch.bind("<Button-1>",self.call_Archive)

        self.labClient = Label(top)
        self.labClient.place(relx=0.0, rely=0.39, height=131, width=154)
        self.labClient.configure(activebackground="#f9f9f9")
        self.labClient.configure(activeforeground="black")
        self.labClient.configure(background="#0b0b1c")
        self.labClient.configure(borderwidth="1")
        self.labClient.configure(cursor="hand2")
        self.labClient.configure(disabledforeground="#a3a3a3")
        self.labClient.configure(font=font9)
        self.labClient.configure(foreground="white")
        self.labClient.configure(highlightbackground="#d9d9d9")
        self.labClient.configure(highlightcolor="black")
        self.labClient.configure(relief=RAISED)
        self.labClient.configure(text='''Clients''')
        self.labClient.bind("<Button-1>",self.call_Client)

        self.labMenu = Label(top)
        self.labMenu.place(relx=0.0, rely=0.0, height=131, width=154)
        self.labMenu.configure(activebackground="#f9f9f9")
        self.labMenu.configure(activeforeground="black")
        self.labMenu.configure(background="#c14915")
        self.labMenu.configure(cursor="hand2")
        self.labMenu.configure(disabledforeground="#a3a3a3")
        self.labMenu.configure(font=font9)
        self.labMenu.configure(foreground="white")
        self.labMenu.configure(highlightbackground="#d9d9d9")
        self.labMenu.configure(highlightcolor="black")
        self.labMenu.configure(text='''Menu''')
        self.labMenu.bind("<Button-1>",self.call_Menu)

        self.labProd = Label(top)
        self.labProd.place(relx=0.0, rely=0.19, height=131, width=154)
        self.labProd.configure(background="#0b0b1c")
        self.labProd.configure(borderwidth="1")
        self.labProd.configure(cursor="hand2")
        self.labProd.configure(disabledforeground="#a3a3a3")
        self.labProd.configure(font=font9)
        self.labProd.configure(foreground="white")
        self.labProd.configure(relief=RAISED)
        self.labProd.configure(text='''Produits''')
        self.labProd.configure(width=154)
        self.labProd.bind("<Button-1>",self.call_Produit)


        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.13, rely=0.0, relheight=0.79, relwidth=0.45)
        self.Frame1.configure(borderwidth="1")
        self.Frame1.configure(background="#c14915")
        self.Frame1.configure(width=445)

        self.labVente = Label(self.Frame1)
        self.labVente.place(relx=0.04, rely=0.11, height=191, width=214)
        self.labVente.configure(background="#c14915")
        self.labVente.configure(borderwidth="1")
        self.labVente.configure(cursor="hand2")
        self.labVente.configure(disabledforeground="#a3a3a3")
        self.labVente.configure(foreground="#000000")
        self._img1 = PhotoImage(file="../image/Buy_96px.png")
        self.labVente.configure(image=self._img1)
        self.labVente.configure(relief=RAISED)
        self.labVente.configure(width=224)

        self.labEntre = Label(self.Frame1)
        self.labEntre.place(relx=0.53, rely=0.12, height=191, width=214)
        self.labEntre.configure(activebackground="#f9f9f9")
        self.labEntre.configure(activeforeground="black")
        self.labEntre.configure(background="#c14915")
        self.labEntre.configure(borderwidth="1")
        self.labEntre.configure(cursor="hand2")
        self.labEntre.configure(disabledforeground="#a3a3a3")
        self.labEntre.configure(foreground="#000000")
        self.labEntre.configure(highlightbackground="#d9d9d9")
        self.labEntre.configure(highlightcolor="black")
        self._img2 = PhotoImage(file="../image/Check Book_96px.png")
        self.labEntre.configure(image=self._img2)
        self.labEntre.configure(relief=RAISED)

        self.labEmp = Label(self.Frame1)
        self.labEmp.place(relx=0.04, rely=0.61, height=191, width=214)
        self.labEmp.configure(activebackground="#f9f9f9")
        self.labEmp.configure(activeforeground="black")
        self.labEmp.configure(background="#c14915")
        self.labEmp.configure(borderwidth="1")
        self.labEmp.configure(cursor="hand2")
        self.labEmp.configure(disabledforeground="#a3a3a3")
        self.labEmp.configure(foreground="#000000")
        self.labEmp.configure(highlightbackground="#d9d9d9")
        self.labEmp.configure(highlightcolor="black")
        self._img3 = PhotoImage(file="../image/Add User Group Man Man_96px.png")
        self.labEmp.configure(image=self._img3)
        self.labEmp.configure(relief=RAISED)

        #self.labAutre = Label(self.Frame1)
        #self.labAutre.place(relx=0.53, rely=0.61, height=191, width=214)
        #self.labAutre.configure(activebackground="#f9f9f9")
        #self.labAutre.configure(activeforeground="black")
        #self.labAutre.configure(background="#c14915")
        #self.labAutre.configure(borderwidth="1")
        #self.labAutre.configure(cursor="hand2")
        #self.labAutre.configure(disabledforeground="#a3a3a3")
        #self.labAutre.configure(foreground="#000000")
        #self.labAutre.configure(highlightbackground="#d9d9d9")
        #self.labAutre.configure(highlightcolor="black")
        #self._img4 = PhotoImage(file="../image/French Fries_96px.png")
        #self.labAutre.configure(image=self._img4)
        #self.labAutre.configure(relief=RAISED)

        self.Label4 = Label(self.Frame1)
        self.Label4.place(relx=0.08, rely=0.04, height=31, width=174)
        self.Label4.configure(background="#c14915")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font=font10)
        self.Label4.configure(foreground="#605b54")
        self.Label4.configure(text='''Faire une Vente''')
        self.Label4.configure(width=174)

        self.Label4_14 = Label(self.Frame1)
        self.Label4_14.place(relx=0.57, rely=0.06, height=31, width=174)
        self.Label4_14.configure(activebackground="#f9f9f9")
        self.Label4_14.configure(activeforeground="black")
        self.Label4_14.configure(background="#c14915")
        self.Label4_14.configure(disabledforeground="#a3a3a3")
        self.Label4_14.configure(font=font10)
        self.Label4_14.configure(foreground="#605b54")
        self.Label4_14.configure(highlightbackground="#d9d9d9")
        self.Label4_14.configure(highlightcolor="black")
        self.Label4_14.configure(text='''Nouvelle Entree''')

        self.Label4_15 = Label(self.Frame1)
        self.Label4_15.place(relx=0.08, rely=0.55, height=31, width=174)
        self.Label4_15.configure(activebackground="#f9f9f9")
        self.Label4_15.configure(activeforeground="black")
        self.Label4_15.configure(background="#c14915")
        self.Label4_15.configure(disabledforeground="#a3a3a3")
        self.Label4_15.configure(font=font10)
        self.Label4_15.configure(foreground="#605b54")
        self.Label4_15.configure(highlightbackground="#d9d9d9")
        self.Label4_15.configure(highlightcolor="black")
        self.Label4_15.configure(text='''Gerer Employes''')

        #self.Label4_16 = Label(self.Frame1)
        #self.Label4_16.place(relx=0.57, rely=0.55, height=31, width=174)
        #self.Label4_16.configure(activebackground="#f9f9f9")
        #self.Label4_16.configure(activeforeground="black")
        #self.Label4_16.configure(background="#c14915")
        #self.Label4_16.configure(disabledforeground="#a3a3a3")
        #self.Label4_16.configure(font=font10)
        #self.Label4_16.configure(foreground="#605b54")
        #self.Label4_16.configure(highlightbackground="#d9d9d9")
        #self.Label4_16.configure(highlightcolor="black")
        #self.Label4_16.configure(text='''Autres''')






if __name__ == '__main__':
    vp_start_gui()



