#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 25, 2018 04:51:45 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import EntreProd_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Nouvelle_Entree_de_Produit (root)
    EntreProd_support.init(root, top)
    root.mainloop()

w = None
def create_Nouvelle_Entree_de_Produit(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Nouvelle_Entree_de_Produit (w)
    EntreProd_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Nouvelle_Entree_de_Produit():
    global w
    w.destroy()
    w = None


class Nouvelle_Entree_de_Produit:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Courier New} -size 14 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 14 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("700x668+376+15")
        top.title("Nouvelle Entree de Produit")
        top.configure(background="#c14915")
        top.configure(width="700")
        top.resizable(0,0)



        self.lab = Label(top)
        self.lab.place(relx=0.33, rely=0.1, height=141, width=184)
        self.lab.configure(background="#c14915")
        self.lab.configure(borderwidth="1")
        self.lab.configure(disabledforeground="#a3a3a3")
        self.lab.configure(foreground="#000000")
        self._img1 = PhotoImage(file="../image/New Product_100px.png")
        self.lab.configure(image=self._img1)
        self.lab.configure(width=184)

        self.Label2 = Label(top)
        self.Label2.place(relx=0.24, rely=0.03, height=31, width=294)
        self.Label2.configure(background="#c14915")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font9)
        self.Label2.configure(foreground="#605b54")
        self.Label2.configure(text='''Enregistrer un  Nouvel Article''')
        self.Label2.configure(width=294)

        self.Label3 = Label(top)
        self.Label3.place(relx=0.17, rely=0.37, height=31, width=194)
        self.Label3.configure(background="#0b0b1c")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font9)
        self.Label3.configure(foreground="#c14915")
        self.Label3.configure(text='''Libele''')
        self.Label3.configure(width=194)

        self.Label3_1 = Label(top)
        self.Label3_1.place(relx=0.17, rely=0.45, height=31, width=194)
        self.Label3_1.configure(activebackground="#f9f9f9")
        self.Label3_1.configure(activeforeground="black")
        self.Label3_1.configure(background="#0b0b1c")
        self.Label3_1.configure(disabledforeground="#a3a3a3")
        self.Label3_1.configure(font=font9)
        self.Label3_1.configure(foreground="#c14915")
        self.Label3_1.configure(highlightbackground="#d9d9d9")
        self.Label3_1.configure(highlightcolor="black")
        self.Label3_1.configure(text='''Designation''')

        self.Label3_2 = Label(top)
        self.Label3_2.place(relx=0.17, rely=0.52, height=31, width=194)
        self.Label3_2.configure(activebackground="#f9f9f9")
        self.Label3_2.configure(activeforeground="black")
        self.Label3_2.configure(background="#0b0b1c")
        self.Label3_2.configure(disabledforeground="#a3a3a3")
        self.Label3_2.configure(font=font9)
        self.Label3_2.configure(foreground="#c14915")
        self.Label3_2.configure(highlightbackground="#d9d9d9")
        self.Label3_2.configure(highlightcolor="black")
        self.Label3_2.configure(text='''Date expiration''')

        self.Label3_3 = Label(top)
        self.Label3_3.place(relx=0.17, rely=0.6, height=31, width=194)
        self.Label3_3.configure(activebackground="#f9f9f9")
        self.Label3_3.configure(activeforeground="black")
        self.Label3_3.configure(background="#0b0b1c")
        self.Label3_3.configure(disabledforeground="#a3a3a3")
        self.Label3_3.configure(font=font9)
        self.Label3_3.configure(foreground="#c14915")
        self.Label3_3.configure(highlightbackground="#d9d9d9")
        self.Label3_3.configure(highlightcolor="black")
        self.Label3_3.configure(text='''Prix Unit Achat''')

        self.Label3_4 = Label(top)
        self.Label3_4.place(relx=0.17, rely=0.67, height=31, width=194)
        self.Label3_4.configure(activebackground="#f9f9f9")
        self.Label3_4.configure(activeforeground="black")
        self.Label3_4.configure(background="#0b0b1c")
        self.Label3_4.configure(disabledforeground="#a3a3a3")
        self.Label3_4.configure(font=font9)
        self.Label3_4.configure(foreground="#c14915")
        self.Label3_4.configure(highlightbackground="#d9d9d9")
        self.Label3_4.configure(highlightcolor="black")
        self.Label3_4.configure(text='''Prix Unit Vente''')

        self.Label3_5 = Label(top)
        self.Label3_5.place(relx=0.17, rely=0.75, height=31, width=194)
        self.Label3_5.configure(activebackground="#f9f9f9")
        self.Label3_5.configure(activeforeground="black")
        self.Label3_5.configure(background="#0b0b1c")
        self.Label3_5.configure(disabledforeground="#a3a3a3")
        self.Label3_5.configure(font=font9)
        self.Label3_5.configure(foreground="#c14915")
        self.Label3_5.configure(highlightbackground="#d9d9d9")
        self.Label3_5.configure(highlightcolor="black")
        self.Label3_5.configure(text='''Quantite''')

        self.txtLib = Entry(top)
        self.txtLib.place(relx=0.51, rely=0.37,height=30, relwidth=0.39)
        self.txtLib.configure(background="#c14915")
        self.txtLib.configure(disabledforeground="#a3a3a3")
        self.txtLib.configure(font=font10)
        self.txtLib.configure(foreground="#0b0b1c")
        self.txtLib.configure(insertbackground="#0b0b1c")
        self.txtLib.configure(justify=CENTER)
        self.txtLib.configure(relief=RAISED)
        self.txtLib.configure(width=274)

        self.txtDes = Entry(top)
        self.txtDes.place(relx=0.51, rely=0.45,height=30, relwidth=0.39)
        self.txtDes.configure(background="#c14915")
        self.txtDes.configure(disabledforeground="#a3a3a3")
        self.txtDes.configure(font=font10)
        self.txtDes.configure(foreground="#0b0b1c")
        self.txtDes.configure(highlightbackground="#d9d9d9")
        self.txtDes.configure(highlightcolor="black")
        self.txtDes.configure(insertbackground="#0b0b1c")
        self.txtDes.configure(justify=CENTER)
        self.txtDes.configure(relief=RAISED)
        self.txtDes.configure(selectbackground="#c4c4c4")
        self.txtDes.configure(selectforeground="black")

        self.txtDte = Entry(top)
        self.txtDte.place(relx=0.51, rely=0.52,height=30, relwidth=0.39)
        self.txtDte.configure(background="#c14915")
        self.txtDte.configure(disabledforeground="#a3a3a3")
        self.txtDte.configure(font=font10)
        self.txtDte.configure(foreground="#0b0b1c")
        self.txtDte.configure(highlightbackground="#d9d9d9")
        self.txtDte.configure(highlightcolor="black")
        self.txtDte.configure(insertbackground="#0b0b1c")
        self.txtDte.configure(justify=CENTER)
        self.txtDte.configure(relief=RAISED)
        self.txtDte.configure(selectbackground="#c4c4c4")
        self.txtDte.configure(selectforeground="black")

        self.txtPua = Entry(top)
        self.txtPua.place(relx=0.51, rely=0.6,height=30, relwidth=0.39)
        self.txtPua.configure(background="#c14915")
        self.txtPua.configure(disabledforeground="#a3a3a3")
        self.txtPua.configure(font=font10)
        self.txtPua.configure(foreground="#0b0b1c")
        self.txtPua.configure(highlightbackground="#d9d9d9")
        self.txtPua.configure(highlightcolor="black")
        self.txtPua.configure(insertbackground="#0b0b1c")
        self.txtPua.configure(justify=CENTER)
        self.txtPua.configure(relief=RAISED)
        self.txtPua.configure(selectbackground="#c4c4c4")
        self.txtPua.configure(selectforeground="black")

        self.txtPuv = Entry(top)
        self.txtPuv.place(relx=0.51, rely=0.67,height=30, relwidth=0.39)
        self.txtPuv.configure(background="#c14915")
        self.txtPuv.configure(disabledforeground="#a3a3a3")
        self.txtPuv.configure(font=font10)
        self.txtPuv.configure(foreground="#0b0b1c")
        self.txtPuv.configure(highlightbackground="#d9d9d9")
        self.txtPuv.configure(highlightcolor="black")
        self.txtPuv.configure(insertbackground="#0b0b1c")
        self.txtPuv.configure(justify=CENTER)
        self.txtPuv.configure(relief=RAISED)
        self.txtPuv.configure(selectbackground="#c4c4c4")
        self.txtPuv.configure(selectforeground="black")

        self.txtQant = Entry(top)
        self.txtQant.place(relx=0.51, rely=0.75,height=30, relwidth=0.39)
        self.txtQant.configure(background="#c14915")
        self.txtQant.configure(disabledforeground="#a3a3a3")
        self.txtQant.configure(font=font10)
        self.txtQant.configure(foreground="#0b0b1c")
        self.txtQant.configure(highlightbackground="#d9d9d9")
        self.txtQant.configure(highlightcolor="black")
        self.txtQant.configure(insertbackground="#0b0b1c")
        self.txtQant.configure(justify=CENTER)
        self.txtQant.configure(relief=RAISED)
        self.txtQant.configure(selectbackground="#c4c4c4")
        self.txtQant.configure(selectforeground="black")

        self.btnSave = Button(top)
        self.btnSave.place(relx=0.57, rely=0.87, height=34, width=187)
        self.btnSave.configure(activebackground="#0b0b1c")
        self.btnSave.configure(activeforeground="white")
        self.btnSave.configure(activeforeground="#c14915")
        self.btnSave.configure(background="#c14915")
        self.btnSave.configure(cursor="hand2")
        self.btnSave.configure(disabledforeground="#a3a3a3")
        self.btnSave.configure(font=font9)
        self.btnSave.configure(foreground="#0b0b1c")
        self.btnSave.configure(highlightbackground="#d9d9d9")
        self.btnSave.configure(highlightcolor="black")
        self.btnSave.configure(pady="0")
        self.btnSave.configure(text='''Enregistrer''')
        self.btnSave.configure(width=187)

        self.btnAnn = Button(top)
        self.btnAnn.place(relx=0.19, rely=0.87, height=34, width=187)
        self.btnAnn.configure(activebackground="#0b0b1c")
        self.btnAnn.configure(activeforeground="white")
        self.btnAnn.configure(activeforeground="#c14915")
        self.btnAnn.configure(background="#c14915")
        self.btnAnn.configure(cursor="hand2")
        self.btnAnn.configure(disabledforeground="#a3a3a3")
        self.btnAnn.configure(font=font9)
        self.btnAnn.configure(foreground="#0b0b1c")
        self.btnAnn.configure(highlightbackground="#d9d9d9")
        self.btnAnn.configure(highlightcolor="black")
        self.btnAnn.configure(pady="0")
        self.btnAnn.configure(text='''Annuler''')






if __name__ == '__main__':
    vp_start_gui()



