#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 25, 2018 08:39:15 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import GereClient_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Liste_des_Clients_ (root)
    GereClient_support.init(root, top)
    root.mainloop()

w = None
def create_Liste_des_Clients_(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Liste_des_Clients_ (w)
    GereClient_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Liste_des_Clients_():
    global w
    w.destroy()
    w = None


class Liste_des_Clients_:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 14 -weight bold -slant "  \
            "roman -underline 1 -overstrike 0"
        font11 = "-family {Courier New} -size 14 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 14 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("1129x668+82+11")
        top.title("Liste des Clients ")
        top.configure(background="#c14915")
        top.resizable(0,0)



        self.Label1 = Label(top)
        self.Label1.place(relx=0.35, rely=0.03, height=41, width=264)
        self.Label1.configure(background="#c14915")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#605b54")
        self.Label1.configure(text='''Gestion des Clients''')
        self.Label1.configure(width=264)

        self.Label2 = Label(top)
        self.Label2.place(relx=0.01, rely=0.1, height=111, width=154)
        self.Label2.configure(background="#c14915")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self._img1 = PhotoImage(file="../image/User Groups_96px.png")
        self.Label2.configure(image=self._img1)
        self.Label2.configure(width=154)

        self.Label3 = Label(top)
        self.Label3.place(relx=0.02, rely=0.31, height=31, width=144)
        self.Label3.configure(background="#0b0b1c")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font10)
        self.Label3.configure(foreground="#c14915")
        self.Label3.configure(text='''Nom ou IFU''')
        self.Label3.configure(width=144)

        self.Label3_1 = Label(top)
        self.Label3_1.place(relx=0.15, rely=0.31, height=31, width=144)
        self.Label3_1.configure(activebackground="#f9f9f9")
        self.Label3_1.configure(activeforeground="black")
        self.Label3_1.configure(background="#0b0b1c")
        self.Label3_1.configure(disabledforeground="#a3a3a3")
        self.Label3_1.configure(font=font10)
        self.Label3_1.configure(foreground="#c14915")
        self.Label3_1.configure(highlightbackground="#d9d9d9")
        self.Label3_1.configure(highlightcolor="black")
        self.Label3_1.configure(text='''Adresse''')

        self.Label3_2 = Label(top)
        self.Label3_2.place(relx=0.28, rely=0.31, height=31, width=144)
        self.Label3_2.configure(activebackground="#f9f9f9")
        self.Label3_2.configure(activeforeground="black")
        self.Label3_2.configure(background="#0b0b1c")
        self.Label3_2.configure(disabledforeground="#a3a3a3")
        self.Label3_2.configure(font=font10)
        self.Label3_2.configure(foreground="#c14915")
        self.Label3_2.configure(highlightbackground="#d9d9d9")
        self.Label3_2.configure(highlightcolor="black")
        self.Label3_2.configure(text='''Contacts''')

        self.listNom = Listbox(top)
        self.listNom.place(relx=0.02, rely=0.36, relheight=0.62, relwidth=0.13)
        self.listNom.configure(background="#c14915")
        self.listNom.configure(cursor="hand2")
        self.listNom.configure(disabledforeground="#a3a3a3")
        self.listNom.configure(font=font11)
        self.listNom.configure(foreground="#0b0b1c")
        self.listNom.configure(justify=CENTER)
        self.listNom.configure(relief=RAISED)
        self.listNom.configure(selectbackground="#0b0b1c")
        self.listNom.configure(selectforeground="#c14915")
        self.listNom.configure(width=144)

        self.listAdr = Listbox(top)
        self.listAdr.place(relx=0.15, rely=0.36, relheight=0.62, relwidth=0.13)
        self.listAdr.configure(background="#c14915")
        self.listAdr.configure(cursor="hand2")
        self.listAdr.configure(disabledforeground="#a3a3a3")
        self.listAdr.configure(font=font11)
        self.listAdr.configure(foreground="#0b0b1c")
        self.listAdr.configure(highlightbackground="#d9d9d9")
        self.listAdr.configure(highlightcolor="black")
        self.listAdr.configure(justify=CENTER)
        self.listAdr.configure(relief=RAISED)
        self.listAdr.configure(selectbackground="#0b0b1c")
        self.listAdr.configure(selectforeground="#c14915")
        self.listAdr.configure(width=144)

        self.listTel = Listbox(top)
        self.listTel.place(relx=0.28, rely=0.36, relheight=0.62, relwidth=0.13)
        self.listTel.configure(background="#c14915")
        self.listTel.configure(cursor="hand2")
        self.listTel.configure(disabledforeground="#a3a3a3")
        self.listTel.configure(font=font11)
        self.listTel.configure(foreground="#0b0b1c")
        self.listTel.configure(highlightbackground="#d9d9d9")
        self.listTel.configure(highlightcolor="black")
        self.listTel.configure(justify=CENTER)
        self.listTel.configure(relief=RAISED)
        self.listTel.configure(selectbackground="#0b0b1c")
        self.listTel.configure(selectforeground="#c14915")
        self.listTel.configure(width=144)

        self.Label3_3 = Label(top)
        self.Label3_3.place(relx=0.54, rely=0.61, height=31, width=144)
        self.Label3_3.configure(activebackground="#f9f9f9")
        self.Label3_3.configure(activeforeground="black")
        self.Label3_3.configure(background="#0b0b1c")
        self.Label3_3.configure(disabledforeground="#a3a3a3")
        self.Label3_3.configure(font=font9)
        self.Label3_3.configure(foreground="#c14915")
        self.Label3_3.configure(highlightbackground="#d9d9d9")
        self.Label3_3.configure(highlightcolor="black")
        self.Label3_3.configure(text='''Nom ou IFU''')

        self.Label3_4 = Label(top)
        self.Label3_4.place(relx=0.54, rely=0.72, height=31, width=144)
        self.Label3_4.configure(activebackground="#f9f9f9")
        self.Label3_4.configure(activeforeground="black")
        self.Label3_4.configure(background="#0b0b1c")
        self.Label3_4.configure(disabledforeground="#a3a3a3")
        self.Label3_4.configure(font=font9)
        self.Label3_4.configure(foreground="#c14915")
        self.Label3_4.configure(highlightbackground="#d9d9d9")
        self.Label3_4.configure(highlightcolor="black")
        self.Label3_4.configure(text='''Adresse''')

        self.Label3_4 = Label(top)
        self.Label3_4.place(relx=0.54, rely=0.82, height=31, width=144)
        self.Label3_4.configure(activebackground="#f9f9f9")
        self.Label3_4.configure(activeforeground="black")
        self.Label3_4.configure(background="#0b0b1c")
        self.Label3_4.configure(disabledforeground="#a3a3a3")
        self.Label3_4.configure(font=font9)
        self.Label3_4.configure(foreground="#c14915")
        self.Label3_4.configure(highlightbackground="#d9d9d9")
        self.Label3_4.configure(highlightcolor="black")
        self.Label3_4.configure(text='''Contacts''')

        self.txtNom = Entry(top)
        self.txtNom.place(relx=0.72, rely=0.61,height=30, relwidth=0.21)
        self.txtNom.configure(background="#c14915")
        self.txtNom.configure(disabledforeground="#a3a3a3")
        self.txtNom.configure(font=font11)
        self.txtNom.configure(foreground="#0b0b1c")
        self.txtNom.configure(insertbackground="#0b0b1c")
        self.txtNom.configure(justify=CENTER)
        self.txtNom.configure(relief=RAISED)
        self.txtNom.configure(width=234)

        self.txtAdr = Entry(top)
        self.txtAdr.place(relx=0.72, rely=0.72,height=30, relwidth=0.21)
        self.txtAdr.configure(background="#c14915")
        self.txtAdr.configure(disabledforeground="#a3a3a3")
        self.txtAdr.configure(font=font11)
        self.txtAdr.configure(foreground="#0b0b1c")
        self.txtAdr.configure(highlightbackground="#d9d9d9")
        self.txtAdr.configure(highlightcolor="black")
        self.txtAdr.configure(insertbackground="#0b0b1c")
        self.txtAdr.configure(justify=CENTER)
        self.txtAdr.configure(relief=RAISED)
        self.txtAdr.configure(selectbackground="#c4c4c4")
        self.txtAdr.configure(selectforeground="black")

        self.txtTel = Entry(top)
        self.txtTel.place(relx=0.72, rely=0.82,height=30, relwidth=0.21)
        self.txtTel.configure(background="#c14915")
        self.txtTel.configure(disabledforeground="#a3a3a3")
        self.txtTel.configure(font=font11)
        self.txtTel.configure(foreground="#0b0b1c")
        self.txtTel.configure(highlightbackground="#d9d9d9")
        self.txtTel.configure(highlightcolor="black")
        self.txtTel.configure(insertbackground="#0b0b1c")
        self.txtTel.configure(justify=CENTER)
        self.txtTel.configure(relief=RAISED)
        self.txtTel.configure(selectbackground="#c4c4c4")
        self.txtTel.configure(selectforeground="black")

        self.btnMod = Button(top)
        self.btnMod.place(relx=0.55, rely=0.91, height=34, width=137)
        self.btnMod.configure(activebackground="#0b0b1c")
        self.btnMod.configure(activeforeground="white")
        self.btnMod.configure(activeforeground="#c14915")
        self.btnMod.configure(background="#c14915")
        self.btnMod.configure(cursor="hand2")
        self.btnMod.configure(disabledforeground="#a3a3a3")
        self.btnMod.configure(font=font9)
        self.btnMod.configure(foreground="#0b0b1c")
        self.btnMod.configure(highlightbackground="#d9d9d9")
        self.btnMod.configure(highlightcolor="black")
        self.btnMod.configure(pady="0")
        self.btnMod.configure(text='''Modifier''')
        self.btnMod.configure(width=137)

        self.btnSup = Button(top)
        self.btnSup.place(relx=0.74, rely=0.91, height=34, width=137)
        self.btnSup.configure(activebackground="#0b0b1c")
        self.btnSup.configure(activeforeground="white")
        self.btnSup.configure(activeforeground="#c14915")
        self.btnSup.configure(background="#c14915")
        self.btnSup.configure(cursor="hand2")
        self.btnSup.configure(disabledforeground="#a3a3a3")
        self.btnSup.configure(font=font9)
        self.btnSup.configure(foreground="#0b0b1c")
        self.btnSup.configure(highlightbackground="#d9d9d9")
        self.btnSup.configure(highlightcolor="black")
        self.btnSup.configure(pady="0")
        self.btnSup.configure(text='''Supprimer''')

        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)








if __name__ == '__main__':
    vp_start_gui()



