#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 25, 2018 06:30:52 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import GereProd_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Gestion_des_Articles (root)
    GereProd_support.init(root, top)
    root.mainloop()

w = None
def create_Gestion_des_Articles(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Gestion_des_Articles (w)
    GereProd_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Gestion_des_Articles():
    global w
    w.destroy()
    w = None


class Gestion_des_Articles:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 14 -weight bold -slant "  \
            "roman -underline 1 -overstrike 0"
        font11 = "-family {Courier New} -size 14 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 14 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("1129x668+81+10")
        top.title("Gestion des Articles")
        top.configure(background="#c14915")
        top.resizable(0,0)



        self.Label1 = Label(top)
        self.Label1.place(relx=0.33, rely=0.04, height=31, width=274)
        self.Label1.configure(background="#c14915")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#605b54")
        self.Label1.configure(text='''Gestion des Articles''')
        self.Label1.configure(width=274)

        self.Label2 = Label(top)
        self.Label2.place(relx=0.02, rely=0.1, height=121, width=154)
        self.Label2.configure(background="#c14915")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self._img1 = PhotoImage(file="../image/Check Book_96px.png")
        self.Label2.configure(image=self._img1)
        self.Label2.configure(width=154)

        self.Label3 = Label(top)
        self.Label3.place(relx=0.01, rely=0.33, height=31, width=154)
        self.Label3.configure(background="#0b0b1c")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font10)
        self.Label3.configure(foreground="#c14915")
        self.Label3.configure(text='''Libele''')
        self.Label3.configure(width=154)

        self.Label3_1 = Label(top)
        self.Label3_1.place(relx=0.15, rely=0.33, height=31, width=234)
        self.Label3_1.configure(activebackground="#f9f9f9")
        self.Label3_1.configure(activeforeground="black")
        self.Label3_1.configure(background="#0b0b1c")
        self.Label3_1.configure(disabledforeground="#a3a3a3")
        self.Label3_1.configure(font=font10)
        self.Label3_1.configure(foreground="#c14915")
        self.Label3_1.configure(highlightbackground="#d9d9d9")
        self.Label3_1.configure(highlightcolor="black")
        self.Label3_1.configure(text='''Designation''')
        self.Label3_1.configure(width=234)

        self.Label3_2 = Label(top)
        self.Label3_2.place(relx=0.36, rely=0.33, height=31, width=154)
        self.Label3_2.configure(activebackground="#f9f9f9")
        self.Label3_2.configure(activeforeground="black")
        self.Label3_2.configure(background="#0b0b1c")
        self.Label3_2.configure(disabledforeground="#a3a3a3")
        self.Label3_2.configure(font=font10)
        self.Label3_2.configure(foreground="#c14915")
        self.Label3_2.configure(highlightbackground="#d9d9d9")
        self.Label3_2.configure(highlightcolor="black")
        self.Label3_2.configure(text='''Date Expiration''')

        self.listLib = Listbox(top)
        self.listLib.place(relx=0.01, rely=0.37, relheight=0.6, relwidth=0.14)
        self.listLib.configure(background="#c14915")
        self.listLib.configure(cursor="hand2")
        self.listLib.configure(disabledforeground="#a3a3a3")
        self.listLib.configure(font=font11)
        self.listLib.configure(foreground="#0b0b1c")
        self.listLib.configure(justify=CENTER)
        self.listLib.configure(relief=RAISED)
        self.listLib.configure(selectbackground="#0b0b1c")
        self.listLib.configure(selectforeground="#c14915")
        self.listLib.configure(width=154)

        self.listDes = Listbox(top)
        self.listDes.place(relx=0.15, rely=0.37, relheight=0.6, relwidth=0.21)
        self.listDes.configure(background="#c14915")
        self.listDes.configure(cursor="hand2")
        self.listDes.configure(disabledforeground="#a3a3a3")
        self.listDes.configure(font=font11)
        self.listDes.configure(foreground="#0b0b1c")
        self.listDes.configure(highlightbackground="#d9d9d9")
        self.listDes.configure(highlightcolor="black")
        self.listDes.configure(justify=CENTER)
        self.listDes.configure(relief=RAISED)
        self.listDes.configure(selectbackground="#0b0b1c")
        self.listDes.configure(selectforeground="#c14915")
        self.listDes.configure(width=234)

        self.listDte = Listbox(top)
        self.listDte.place(relx=0.36, rely=0.37, relheight=0.6, relwidth=0.14)
        self.listDte.configure(background="#c14915")
        self.listDte.configure(cursor="hand2")
        self.listDte.configure(disabledforeground="#a3a3a3")
        self.listDte.configure(font=font11)
        self.listDte.configure(foreground="#0b0b1c")
        self.listDte.configure(highlightbackground="#d9d9d9")
        self.listDte.configure(highlightcolor="black")
        self.listDte.configure(justify=CENTER)
        self.listDte.configure(relief=RAISED)
        self.listDte.configure(selectbackground="#0b0b1c")
        self.listDte.configure(selectforeground="#c14915")
        self.listDte.configure(width=154)

        self.Label3_3 = Label(top)
        self.Label3_3.place(relx=0.58, rely=0.37, height=31, width=184)
        self.Label3_3.configure(activebackground="#f9f9f9")
        self.Label3_3.configure(activeforeground="black")
        self.Label3_3.configure(background="#0b0b1c")
        self.Label3_3.configure(disabledforeground="#a3a3a3")
        self.Label3_3.configure(font=font9)
        self.Label3_3.configure(foreground="#c14915")
        self.Label3_3.configure(highlightbackground="#d9d9d9")
        self.Label3_3.configure(highlightcolor="black")
        self.Label3_3.configure(text='''Libele''')
        self.Label3_3.configure(width=184)

        self.Label3_4 = Label(top)
        self.Label3_4.place(relx=0.58, rely=0.46, height=31, width=184)
        self.Label3_4.configure(activebackground="#f9f9f9")
        self.Label3_4.configure(activeforeground="black")
        self.Label3_4.configure(background="#0b0b1c")
        self.Label3_4.configure(disabledforeground="#a3a3a3")
        self.Label3_4.configure(font=font9)
        self.Label3_4.configure(foreground="#c14915")
        self.Label3_4.configure(highlightbackground="#d9d9d9")
        self.Label3_4.configure(highlightcolor="black")
        self.Label3_4.configure(text='''Designation''')

        self.Label3_4 = Label(top)
        self.Label3_4.place(relx=0.58, rely=0.55, height=31, width=184)
        self.Label3_4.configure(activebackground="#f9f9f9")
        self.Label3_4.configure(activeforeground="black")
        self.Label3_4.configure(background="#0b0b1c")
        self.Label3_4.configure(disabledforeground="#a3a3a3")
        self.Label3_4.configure(font=font9)
        self.Label3_4.configure(foreground="#c14915")
        self.Label3_4.configure(highlightbackground="#d9d9d9")
        self.Label3_4.configure(highlightcolor="black")
        self.Label3_4.configure(text='''Prix Unit Achat''')

        self.Label3_4 = Label(top)
        self.Label3_4.place(relx=0.58, rely=0.64, height=31, width=184)
        self.Label3_4.configure(activebackground="#f9f9f9")
        self.Label3_4.configure(activeforeground="black")
        self.Label3_4.configure(background="#0b0b1c")
        self.Label3_4.configure(disabledforeground="#a3a3a3")
        self.Label3_4.configure(font=font9)
        self.Label3_4.configure(foreground="#c14915")
        self.Label3_4.configure(highlightbackground="#d9d9d9")
        self.Label3_4.configure(highlightcolor="black")
        self.Label3_4.configure(text='''Prix Unit Vente''')

        self.Label3_4 = Label(top)
        self.Label3_4.place(relx=0.58, rely=0.73, height=31, width=184)
        self.Label3_4.configure(activebackground="#f9f9f9")
        self.Label3_4.configure(activeforeground="black")
        self.Label3_4.configure(background="#0b0b1c")
        self.Label3_4.configure(disabledforeground="#a3a3a3")
        self.Label3_4.configure(font=font9)
        self.Label3_4.configure(foreground="#c14915")
        self.Label3_4.configure(highlightbackground="#d9d9d9")
        self.Label3_4.configure(highlightcolor="black")
        self.Label3_4.configure(text='''Quantite''')

        self.Label3_4 = Label(top)
        self.Label3_4.place(relx=0.58, rely=0.82, height=31, width=184)
        self.Label3_4.configure(activebackground="#f9f9f9")
        self.Label3_4.configure(activeforeground="black")
        self.Label3_4.configure(background="#0b0b1c")
        self.Label3_4.configure(disabledforeground="#a3a3a3")
        self.Label3_4.configure(font=font9)
        self.Label3_4.configure(foreground="#c14915")
        self.Label3_4.configure(highlightbackground="#d9d9d9")
        self.Label3_4.configure(highlightcolor="black")
        self.Label3_4.configure(text='''Date Expiration''')

        self.txtLib = Entry(top)
        self.txtLib.place(relx=0.77, rely=0.37,height=30, relwidth=0.2)
        self.txtLib.configure(background="#c14915")
        self.txtLib.configure(disabledforeground="#a3a3a3")
        self.txtLib.configure(font=font11)
        self.txtLib.configure(foreground="#0b0b1c")
        self.txtLib.configure(insertbackground="#0b0b1c")
        self.txtLib.configure(justify=CENTER)
        self.txtLib.configure(relief=RAISED)
        self.txtLib.configure(width=224)

        self.txtDes = Entry(top)
        self.txtDes.place(relx=0.77, rely=0.46,height=30, relwidth=0.2)
        self.txtDes.configure(background="#c14915")
        self.txtDes.configure(disabledforeground="#a3a3a3")
        self.txtDes.configure(font=font11)
        self.txtDes.configure(foreground="#0b0b1c")
        self.txtDes.configure(highlightbackground="#d9d9d9")
        self.txtDes.configure(highlightcolor="black")
        self.txtDes.configure(insertbackground="#0b0b1c")
        self.txtDes.configure(justify=CENTER)
        self.txtDes.configure(relief=RAISED)
        self.txtDes.configure(selectbackground="#c4c4c4")
        self.txtDes.configure(selectforeground="black")

        self.txtPua = Entry(top)
        self.txtPua.place(relx=0.77, rely=0.55,height=30, relwidth=0.2)
        self.txtPua.configure(background="#c14915")
        self.txtPua.configure(disabledforeground="#a3a3a3")
        self.txtPua.configure(font=font11)
        self.txtPua.configure(foreground="#0b0b1c")
        self.txtPua.configure(highlightbackground="#d9d9d9")
        self.txtPua.configure(highlightcolor="black")
        self.txtPua.configure(insertbackground="#0b0b1c")
        self.txtPua.configure(justify=CENTER)
        self.txtPua.configure(relief=RAISED)
        self.txtPua.configure(selectbackground="#c4c4c4")
        self.txtPua.configure(selectforeground="black")

        self.txtPuv = Entry(top)
        self.txtPuv.place(relx=0.77, rely=0.64,height=30, relwidth=0.2)
        self.txtPuv.configure(background="#c14915")
        self.txtPuv.configure(disabledforeground="#a3a3a3")
        self.txtPuv.configure(font=font11)
        self.txtPuv.configure(foreground="#0b0b1c")
        self.txtPuv.configure(highlightbackground="#d9d9d9")
        self.txtPuv.configure(highlightcolor="black")
        self.txtPuv.configure(insertbackground="#0b0b1c")
        self.txtPuv.configure(justify=CENTER)
        self.txtPuv.configure(relief=RAISED)
        self.txtPuv.configure(selectbackground="#c4c4c4")
        self.txtPuv.configure(selectforeground="black")

        self.txtQuan = Entry(top)
        self.txtQuan.place(relx=0.77, rely=0.73,height=30, relwidth=0.2)
        self.txtQuan.configure(background="#c14915")
        self.txtQuan.configure(disabledforeground="#a3a3a3")
        self.txtQuan.configure(font=font11)
        self.txtQuan.configure(foreground="#0b0b1c")
        self.txtQuan.configure(highlightbackground="#d9d9d9")
        self.txtQuan.configure(highlightcolor="black")
        self.txtQuan.configure(insertbackground="#0b0b1c")
        self.txtQuan.configure(justify=CENTER)
        self.txtQuan.configure(relief=RAISED)
        self.txtQuan.configure(selectbackground="#c4c4c4")
        self.txtQuan.configure(selectforeground="black")

        self.txtDte = Entry(top)
        self.txtDte.place(relx=0.77, rely=0.82,height=30, relwidth=0.2)
        self.txtDte.configure(background="#c14915")
        self.txtDte.configure(disabledforeground="#a3a3a3")
        self.txtDte.configure(font=font11)
        self.txtDte.configure(foreground="#0b0b1c")
        self.txtDte.configure(highlightbackground="#d9d9d9")
        self.txtDte.configure(highlightcolor="black")
        self.txtDte.configure(insertbackground="#0b0b1c")
        self.txtDte.configure(justify=CENTER)
        self.txtDte.configure(relief=RAISED)
        self.txtDte.configure(selectbackground="#c4c4c4")
        self.txtDte.configure(selectforeground="black")

        self.btnSup = Button(top)
        self.btnSup.place(relx=0.58, rely=0.91, height=34, width=147)
        self.btnSup.configure(activebackground="#0b0b1c")
        self.btnSup.configure(activeforeground="white")
        self.btnSup.configure(activeforeground="#c14915")
        self.btnSup.configure(background="#c14915")
        self.btnSup.configure(cursor="hand2")
        self.btnSup.configure(disabledforeground="#a3a3a3")
        self.btnSup.configure(font=font9)
        self.btnSup.configure(foreground="#0b0b1c")
        self.btnSup.configure(highlightbackground="#d9d9d9")
        self.btnSup.configure(highlightcolor="black")
        self.btnSup.configure(pady="0")
        self.btnSup.configure(text='''Supprimer''')
        self.btnSup.configure(width=147)

        self.btnMod = Button(top)
        self.btnMod.place(relx=0.72, rely=0.91, height=34, width=147)
        self.btnMod.configure(activebackground="#0b0b1c")
        self.btnMod.configure(activeforeground="white")
        self.btnMod.configure(activeforeground="#c14915")
        self.btnMod.configure(background="#c14915")
        self.btnMod.configure(cursor="hand2")
        self.btnMod.configure(disabledforeground="#a3a3a3")
        self.btnMod.configure(font=font9)
        self.btnMod.configure(foreground="#0b0b1c")
        self.btnMod.configure(highlightbackground="#d9d9d9")
        self.btnMod.configure(highlightcolor="black")
        self.btnMod.configure(pady="0")
        self.btnMod.configure(text='''Modifier''')

        self.btnEnre = Button(top)
        self.btnEnre.place(relx=0.86, rely=0.91, height=34, width=147)
        self.btnEnre.configure(activebackground="#0b0b1c")
        self.btnEnre.configure(activeforeground="white")
        self.btnEnre.configure(activeforeground="#c14915")
        self.btnEnre.configure(background="#c14915")
        self.btnEnre.configure(cursor="hand2")
        self.btnEnre.configure(disabledforeground="#a3a3a3")
        self.btnEnre.configure(font=font9)
        self.btnEnre.configure(foreground="#0b0b1c")
        self.btnEnre.configure(highlightbackground="#d9d9d9")
        self.btnEnre.configure(highlightcolor="black")
        self.btnEnre.configure(pady="0")
        self.btnEnre.configure(text='''Enregistrer''')






if __name__ == '__main__':
    vp_start_gui()



