#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 25, 2018 06:02:47 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import InventProd_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Liste_exhaustive_des_Articles_de_la_Base_de_Donnees (root)
    InventProd_support.init(root, top)
    root.mainloop()

w = None
def create_Liste_exhaustive_des_Articles_de_la_Base_de_Donnees(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Liste_exhaustive_des_Articles_de_la_Base_de_Donnees (w)
    InventProd_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Liste_exhaustive_des_Articles_de_la_Base_de_Donnees():
    global w
    w.destroy()
    w = None


class Liste_exhaustive_des_Articles_de_la_Base_de_Donnees:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 14 -weight bold -slant "  \
            "roman -underline 1 -overstrike 0"
        font11 = "-family {Courier New} -size 14 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 14 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("1129x668+80+11")
        top.title("Liste exhaustive des Articles de la Base de Donnees")
        top.configure(background="#c14915")
        top.resizable(0,0)



        self.Label1 = Label(top)
        self.Label1.place(relx=0.37, rely=0.03, height=31, width=314)
        self.Label1.configure(background="#c14915")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#605b54")
        self.Label1.configure(text='''Liste Complete Articles''')
        self.Label1.configure(width=314)

        self.Label2 = Label(top)
        self.Label2.place(relx=0.02, rely=0.07, height=121, width=154)
        self.Label2.configure(background="#c14915")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self._img1 = PhotoImage(file="../image/French Fries_96px.png")
        self.Label2.configure(image=self._img1)
        self.Label2.configure(width=154)

        self.Label3 = Label(top)
        self.Label3.place(relx=0.02, rely=0.28, height=31, width=204)
        self.Label3.configure(background="#0b0b1c")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font10)
        self.Label3.configure(foreground="#c14915")
        self.Label3.configure(text='''Libele''')
        self.Label3.configure(width=204)

        self.Label3_1 = Label(top)
        self.Label3_1.place(relx=0.2, rely=0.28, height=31, width=274)
        self.Label3_1.configure(activebackground="#f9f9f9")
        self.Label3_1.configure(activeforeground="black")
        self.Label3_1.configure(background="#0b0b1c")
        self.Label3_1.configure(disabledforeground="#a3a3a3")
        self.Label3_1.configure(font=font10)
        self.Label3_1.configure(foreground="#c14915")
        self.Label3_1.configure(highlightbackground="#d9d9d9")
        self.Label3_1.configure(highlightcolor="black")
        self.Label3_1.configure(text='''Designation''')
        self.Label3_1.configure(width=274)

        self.Label3_2 = Label(top)
        self.Label3_2.place(relx=0.45, rely=0.28, height=31, width=124)
        self.Label3_2.configure(activebackground="#f9f9f9")
        self.Label3_2.configure(activeforeground="black")
        self.Label3_2.configure(background="#0b0b1c")
        self.Label3_2.configure(disabledforeground="#a3a3a3")
        self.Label3_2.configure(font=font10)
        self.Label3_2.configure(foreground="#c14915")
        self.Label3_2.configure(highlightbackground="#d9d9d9")
        self.Label3_2.configure(highlightcolor="black")
        self.Label3_2.configure(text='''Prix  Achat''')
        self.Label3_2.configure(width=124)

        self.Label3_3 = Label(top)
        self.Label3_3.place(relx=0.57, rely=0.28, height=31, width=124)
        self.Label3_3.configure(activebackground="#f9f9f9")
        self.Label3_3.configure(activeforeground="black")
        self.Label3_3.configure(background="#0b0b1c")
        self.Label3_3.configure(disabledforeground="#a3a3a3")
        self.Label3_3.configure(font=font10)
        self.Label3_3.configure(foreground="#c14915")
        self.Label3_3.configure(highlightbackground="#d9d9d9")
        self.Label3_3.configure(highlightcolor="black")
        self.Label3_3.configure(text='''Prix Vente''')
        self.Label3_3.configure(width=124)

        self.Label3_4 = Label(top)
        self.Label3_4.place(relx=0.68, rely=0.28, height=31, width=104)
        self.Label3_4.configure(activebackground="#f9f9f9")
        self.Label3_4.configure(activeforeground="black")
        self.Label3_4.configure(background="#0b0b1c")
        self.Label3_4.configure(disabledforeground="#a3a3a3")
        self.Label3_4.configure(font=font10)
        self.Label3_4.configure(foreground="#c14915")
        self.Label3_4.configure(highlightbackground="#d9d9d9")
        self.Label3_4.configure(highlightcolor="black")
        self.Label3_4.configure(text='''Quantite''')
        self.Label3_4.configure(width=104)

        self.Label3_5 = Label(top)
        self.Label3_5.place(relx=0.78, rely=0.28, height=31, width=204)
        self.Label3_5.configure(activebackground="#f9f9f9")
        self.Label3_5.configure(activeforeground="black")
        self.Label3_5.configure(background="#0b0b1c")
        self.Label3_5.configure(disabledforeground="#a3a3a3")
        self.Label3_5.configure(font=font10)
        self.Label3_5.configure(foreground="#c14915")
        self.Label3_5.configure(highlightbackground="#d9d9d9")
        self.Label3_5.configure(highlightcolor="black")
        self.Label3_5.configure(text='''Date Expiration''')

        self.listLib = Listbox(top)
        self.listLib.place(relx=0.02, rely=0.33, relheight=0.6, relwidth=0.18)
        self.listLib.configure(background="#c14915")
        self.listLib.configure(cursor="hand2")
        self.listLib.configure(disabledforeground="#a3a3a3")
        self.listLib.configure(font=font11)
        self.listLib.configure(foreground="#0b0b1c")
        self.listLib.configure(justify=CENTER)
        self.listLib.configure(relief=RAISED)
        self.listLib.configure(selectbackground="#0b0b1c")
        self.listLib.configure(selectforeground="#c14915")
        self.listLib.configure(width=204)

        self.listDes = Listbox(top)
        self.listDes.place(relx=0.2, rely=0.33, relheight=0.6, relwidth=0.24)
        self.listDes.configure(background="#c14915")
        self.listDes.configure(cursor="hand2")
        self.listDes.configure(disabledforeground="#a3a3a3")
        self.listDes.configure(font=font11)
        self.listDes.configure(foreground="#0b0b1c")
        self.listDes.configure(highlightbackground="#d9d9d9")
        self.listDes.configure(highlightcolor="black")
        self.listDes.configure(justify=CENTER)
        self.listDes.configure(relief=RAISED)
        self.listDes.configure(selectbackground="#0b0b1c")
        self.listDes.configure(selectforeground="#c14915")
        self.listDes.configure(width=274)

        self.listPua = Listbox(top)
        self.listPua.place(relx=0.45, rely=0.33, relheight=0.6, relwidth=0.11)
        self.listPua.configure(background="#c14915")
        self.listPua.configure(cursor="hand2")
        self.listPua.configure(disabledforeground="#a3a3a3")
        self.listPua.configure(font=font11)
        self.listPua.configure(foreground="#0b0b1c")
        self.listPua.configure(highlightbackground="#d9d9d9")
        self.listPua.configure(highlightcolor="black")
        self.listPua.configure(justify=CENTER)
        self.listPua.configure(relief=RAISED)
        self.listPua.configure(selectbackground="#0b0b1c")
        self.listPua.configure(selectforeground="#c14915")
        self.listPua.configure(width=124)

        self.listPuv = Listbox(top)
        self.listPuv.place(relx=0.57, rely=0.33, relheight=0.6, relwidth=0.11)
        self.listPuv.configure(background="#c14915")
        self.listPuv.configure(cursor="hand2")
        self.listPuv.configure(disabledforeground="#a3a3a3")
        self.listPuv.configure(font=font11)
        self.listPuv.configure(foreground="#0b0b1c")
        self.listPuv.configure(highlightbackground="#d9d9d9")
        self.listPuv.configure(highlightcolor="black")
        self.listPuv.configure(justify=CENTER)
        self.listPuv.configure(relief=RAISED)
        self.listPuv.configure(selectbackground="#0b0b1c")
        self.listPuv.configure(selectforeground="#c14915")
        self.listPuv.configure(width=124)

        self.listQuan = Listbox(top)
        self.listQuan.place(relx=0.68, rely=0.33, relheight=0.6, relwidth=0.09)
        self.listQuan.configure(background="#c14915")
        self.listQuan.configure(cursor="hand2")
        self.listQuan.configure(disabledforeground="#a3a3a3")
        self.listQuan.configure(font=font11)
        self.listQuan.configure(foreground="#0b0b1c")
        self.listQuan.configure(highlightbackground="#d9d9d9")
        self.listQuan.configure(highlightcolor="black")
        self.listQuan.configure(justify=CENTER)
        self.listQuan.configure(relief=RAISED)
        self.listQuan.configure(selectbackground="#0b0b1c")
        self.listQuan.configure(selectforeground="#c14915")
        self.listQuan.configure(width=104)

        self.listDte = Listbox(top)
        self.listDte.place(relx=0.78, rely=0.33, relheight=0.6, relwidth=0.18)
        self.listDte.configure(background="#c14915")
        self.listDte.configure(cursor="hand2")
        self.listDte.configure(disabledforeground="#a3a3a3")
        self.listDte.configure(font=font11)
        self.listDte.configure(foreground="#0b0b1c")
        self.listDte.configure(highlightbackground="#d9d9d9")
        self.listDte.configure(highlightcolor="black")
        self.listDte.configure(justify=CENTER)
        self.listDte.configure(relief=RAISED)
        self.listDte.configure(selectbackground="#0b0b1c")
        self.listDte.configure(selectforeground="#c14915")
        self.listDte.configure(width=204)

        self.btnPrint = Button(top)
        self.btnPrint.place(relx=0.42, rely=0.94, height=34, width=177)
        self.btnPrint.configure(activebackground="#0b0b1c")
        self.btnPrint.configure(activeforeground="white")
        self.btnPrint.configure(activeforeground="#c14915")
        self.btnPrint.configure(background="#c14915")
        self.btnPrint.configure(cursor="hand2")
        self.btnPrint.configure(disabledforeground="#a3a3a3")
        self.btnPrint.configure(font=font9)
        self.btnPrint.configure(foreground="#0b0b1c")
        self.btnPrint.configure(highlightbackground="#d9d9d9")
        self.btnPrint.configure(highlightcolor="black")
        self.btnPrint.configure(pady="0")
        self.btnPrint.configure(text='''Imprimer''')
        self.btnPrint.configure(width=177)






if __name__ == '__main__':
    vp_start_gui()



