#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 25, 2018 02:50:04 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Load_support,time

j,i=0,0
tm=0
IMAGE = ['../image/load1.png','../image/load2.png','../image/load3.png','../image/load4.png','../image/load5.png','../image/load6.png','../image/load7.png','../image/load8.png']

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Chargement (root)
    Load_support.init(root, top)
    root.mainloop()

w = None
def create_Chargement(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Chargement (w)
    Load_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Chargement():
    global w
    w.destroy()
    w = None


class Chargement:
    def loading(self):
        global tm,IMAGE,i,j
        
        while(i<=10):
            while(j<8):
                self._img1.configure(file=IMAGE[j])
                #time.sleep(0.2)
                j+=1
            tm=10*i
            self.labLoad.configure(text=str(tm)+'%')
            #time.sleep(1)
            i+=1   

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font11 = "-family {Segoe UI} -size 24 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 14 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("600x316+437+216")
        top.title("Chargement")
        top.configure(borderwidth="2")
        top.configure(relief="raised")
        top.configure(background="#c14915")
        top.overrideredirect(1)



        self.Label1 = Label(top)
        self.Label1.place(relx=0.22, rely=0.06, height=41, width=324)
        self.Label1.configure(background="#c14915")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#605b54")
        self.Label1.configure(text='''Chargement en cours ...''')
        self.Label1.configure(width=324)

        self.labLoad = Label(top)
        self.labLoad.place(relx=0.37, rely=0.7, height=71, width=114)
        self.labLoad.configure(activebackground="#f9f9f9")
        self.labLoad.configure(activeforeground="black")
        self.labLoad.configure(background="#c14915")
        self.labLoad.configure(disabledforeground="#a3a3a3")
        self.labLoad.configure(font=font11)
        self.labLoad.configure(foreground="#605b54")
        self.labLoad.configure(highlightbackground="#d9d9d9")
        self.labLoad.configure(highlightcolor="black")
        self.labLoad.configure(text='''100%''')
        self.labLoad.configure(width=114)

        self.labImg = Label(top)
        self.labImg.place(relx=0.3, rely=0.32, height=121, width=204)
        self.labImg.configure(activebackground="#f9f9f9")
        self.labImg.configure(activeforeground="black")
        self.labImg.configure(background="#c14915")
        self.labImg.configure(disabledforeground="#a3a3a3")
        self.labImg.configure(font=font11)
        self.labImg.configure(foreground="#605b54")
        self.labImg.configure(highlightbackground="#d9d9d9")
        self.labImg.configure(highlightcolor="black")
        self._img1 = PhotoImage(file="../image/load1.png")
        self.labImg.configure(image=self._img1)
        self.labImg.configure(width=204)
        self.loading()






if __name__ == '__main__':
    vp_start_gui()



