#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 25, 2018 09:11:06 AM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Login_support,Accueil

VI=0

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Connexion (root)
    Login_support.init(root, top)
    root.mainloop()

w = None
def create_Connexion(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Connexion (w)
    Login_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Connexion():
    global w
    w.destroy()
    w = None


class Connexion:
    def LogIn(self,event):
        if(self.txtLog.get() != 'zcorp' or self.txtPass.get() != 'tooro'):
            self.labAlert.configure(text='Utilisateur ou Mot de Passe INCORRECT !!!')
        else:
            self.labAlert.configure(text='')
            Accueil.create_Menu_Principal(root)
            destroy_Connexion()   
    def Quitter(self,event):
        exit()
    def visible(self,event):
        global VI
        if(VI):
            self.txtPass.configure(show="")
            VI=0
        else:
            self.txtPass.configure(show="*")    
            VI=1

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family Tahoma -size 14 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"
        font11 = "-family Corbel -size 15 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"
        font12 = "-family System -size 10 -weight bold -slant roman "  \
            "-underline 1 -overstrike 0"

        top.geometry("466x450+475+128")
        top.title("Connexion")
        top.configure(background="#c14915")
        top.resizable(0,0)
        top.overrideredirect(1)



        self.Label1 = Label(top)
        self.Label1.place(relx=0.3, rely=0.16, height=151, width=184)
        self.Label1.configure(background="#c14915")
        self.Label1.configure(borderwidth="1")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self._img1 = PhotoImage(file="../image/Guest Male_96px.png")
        self.Label1.configure(image=self._img1)
        self.Label1.configure(relief=RAISED)
        self.Label1.configure(text='''Label''')
        self.Label1.configure(width=184)

        self.Label2 = Label(top)
        self.Label2.place(relx=0.0, rely=0.58, height=41, width=204)
        self.Label2.configure(background="#0b0b1c")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font10)
        self.Label2.configure(foreground="#c14915")
        self.Label2.configure(relief=RAISED)
        self.Label2.configure(text='''Nom Utilisateur :''')
        self.Label2.configure(width=204)

        self.Label2_1 = Label(top)
        self.Label2_1.place(relx=0.0, rely=0.69, height=41, width=204)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#0b0b1c")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font=font10)
        self.Label2_1.configure(foreground="#c14915")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(relief=RAISED)
        self.Label2_1.configure(text='''Mot de Passe :''')

        self.Label3 = Label(top)
        self.Label3.place(relx=0.02, rely=0.07, height=31, width=394)
        self.Label3.configure(background="#c14915")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font10)
        self.Label3.configure(foreground="#605b54")
        self.Label3.configure(text='''Se Connecter pour Utiliser le Logiciel''')
        self.Label3.configure(width=394)

        self.txtLog = Entry(top)
        self.txtLog.place(relx=0.47, rely=0.58,height=40, relwidth=0.5)
        self.txtLog.configure(background="#c14915")
        self.txtLog.configure(borderwidth="2")
        self.txtLog.configure(disabledforeground="#a3a3a3")
        self.txtLog.configure(font=font11)
        self.txtLog.configure(foreground="#0b0b1c")
        self.txtLog.configure(insertbackground="#0b0b1c")
        self.txtLog.configure(justify=CENTER)
        self.txtLog.configure(relief=RAISED)
        self.txtLog.configure(width=234)

        self.txtPass = Entry(top)
        self.txtPass.place(relx=0.47, rely=0.69,height=40, relwidth=0.5)
        self.txtPass.configure(background="#c14915")
        self.txtPass.configure(borderwidth="2")
        self.txtPass.configure(disabledforeground="#a3a3a3")
        self.txtPass.configure(font=font11)
        self.txtPass.configure(foreground="#0b0b1c")
        self.txtPass.configure(highlightbackground="#d9d9d9")
        self.txtPass.configure(highlightcolor="black")
        self.txtPass.configure(insertbackground="#0b0b1c")
        self.txtPass.configure(justify=CENTER)
        self.txtPass.configure(relief=RAISED)
        self.txtPass.configure(selectbackground="#c4c4c4")
        self.txtPass.configure(selectforeground="black")
        self.txtPass.configure(show="*")

        self.btnLog = Label(top)
        self.btnLog.place(relx=0.84, rely=0.78, height=51, width=64)
        self.btnLog.configure(background="#c14915")
        self.btnLog.configure(borderwidth="1")
        self.btnLog.configure(cursor="hand2")
        self.btnLog.configure(disabledforeground="#a3a3a3")
        self.btnLog.configure(foreground="#000000")
        self._img2 = PhotoImage(file="../image/Sort Right_48px.png")
        self.btnLog.configure(image=self._img2)
        self.btnLog.configure(relief=RAISED)
        self.btnLog.configure(width=64)
        self.btnLog.bind('<Button-1>',self.LogIn)
        self.btnLog.bind('<Return>',self.LogIn)

        self.labAlert = Label(top)
        self.labAlert.place(relx=0.02, rely=0.91, height=31, width=324)
        self.labAlert.configure(background="#c14915")
        self.labAlert.configure(disabledforeground="#a3a3a3")
        self.labAlert.configure(font=font12)
        self.labAlert.configure(foreground="#0b0b1c")
        self.labAlert.configure(text='''''')
        self.labAlert.configure(width=324)

        self.btnVisible = Label(top)
        self.btnVisible.place(relx=0.69, rely=0.78, height=41, width=54)
        self.btnVisible.configure(activebackground="#f9f9f9")
        self.btnVisible.configure(activeforeground="black")
        self.btnVisible.configure(background="#c14915")
        self.btnVisible.configure(borderwidth="1")
        self.btnVisible.configure(cursor="hand2")
        self.btnVisible.configure(disabledforeground="#a3a3a3")
        self.btnVisible.configure(foreground="#000000")
        self.btnVisible.configure(highlightbackground="#d9d9d9")
        self.btnVisible.configure(highlightcolor="black")
        self._img3 = PhotoImage(file="../image/Visible_50px.png")
        self.btnVisible.configure(image=self._img3)
        self.btnVisible.configure(width=54)
        self.btnVisible.bind('<Button-1>',self.visible)

        self.btnQuit = Label(top)
        self.btnQuit.place(relx=0.88, rely=0.0, height=41, width=54)
        self.btnQuit.configure(background="#c14915")
        self.btnQuit.configure(cursor="hand2")
        self.btnQuit.configure(disabledforeground="#a3a3a3")
        self.btnQuit.configure(foreground="#000000")
        self._img4 = PhotoImage(file="../image/Close Window_48px.png")
        self.btnQuit.configure(image=self._img4)
        self.btnQuit.configure(width=54)
        self.btnQuit.bind('<Button-1>',self.Quitter)






if __name__ == '__main__':
    vp_start_gui()



